server:
  port: 8085
spring:
  application:
    name: scheduler-rest
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.mail.ru
    password: F06dqk6Q2ACYxJBtdxxq
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: nikola_doma@mail.ru